# Generated by Django 3.2.9 on 2021-11-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
